experiment_name: "AIGCIQA2023_Quality_Task"
device: "cuda:0"
seed: 20260221

dataset_name: "AIGCIQA2023"
task_type: "quality"

img_dir: "./dataset/AIGCIQA2023/image"
train_csv: "./dataset/AIGCIQA2023/quality/train.csv"
val_csv: "./dataset/AIGCIQA2023/quality/val.csv"

reiqa_root: "./ReIQA_main"
cache_root: "./cache_reiqa_feats"

clip_model_name: "ViT-B/32"
freeze_opt: 0

batch_size: 16
num_workers: 16
#12 is better
train_num_patch: 8
val_num_patch: 15

clip_lr: 0.000005
tcpga_lr: 0.00005
prior_gate_lr: 0.00001
full_mod_lr: 0.00005

clip_weight_decay: 0.001
others_weight_decay: 0.0

epochs: 25
scheduler_mode: "warmup_cosine"
warmup_epochs: 3
cosine_eta_min_factor: 0.2

checkpoint_dir: "./checkpoints/AIGCIQA2023/quality"
